-- generated by Digital. Don't modify this file!
-- Any changes will be lost if this file is regenerated.

LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_1 is
  port (
    p_out: out std_logic;
    sel: in std_logic;
    
    in_0: in std_logic;
    in_1: in std_logic );
end MUX_GATE_1;

architecture Behavioral of MUX_GATE_1 is
begin
  with sel select
    p_out <=
      in_0 when '0',
      in_1 when '1',
      '0' when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_BUS_1 is
  generic ( Bits : integer ); 
  port (
    p_out: out std_logic_vector ((Bits-1) downto 0);
    sel: in std_logic;
    
    in_0: in std_logic_vector ((Bits-1) downto 0);
    in_1: in std_logic_vector ((Bits-1) downto 0) );
end MUX_GATE_BUS_1;

architecture Behavioral of MUX_GATE_BUS_1 is
begin
  with sel select
    p_out <=
      in_0 when '0',
      in_1 when '1',
      (others => '0') when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_BUS_2 is
  generic ( Bits : integer ); 
  port (
    p_out: out std_logic_vector ((Bits-1) downto 0);
    sel: in std_logic_vector (1 downto 0);
    
    in_0: in std_logic_vector ((Bits-1) downto 0);
    in_1: in std_logic_vector ((Bits-1) downto 0);
    in_2: in std_logic_vector ((Bits-1) downto 0);
    in_3: in std_logic_vector ((Bits-1) downto 0) );
end MUX_GATE_BUS_2;

architecture Behavioral of MUX_GATE_BUS_2 is
begin
  with sel select
    p_out <=
      in_0 when "00",
      in_1 when "01",
      in_2 when "10",
      in_3 when "11",
      (others => '0') when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.std_logic_unsigned.all;

entity DIG_Add is
  generic ( Bits: integer ); 
  port (
    s: out std_logic_vector((Bits-1) downto 0);
    c_o: out std_logic;
    a: in std_logic_vector((Bits-1) downto 0);
    b: in std_logic_vector((Bits-1) downto 0);
    c_i: in std_logic );
end DIG_Add;

architecture Behavioral of DIG_Add is
   signal temp : std_logic_vector(Bits downto 0);
begin
   temp <= ('0' & a) + b + c_i;

   s    <= temp((Bits-1) downto 0);
   c_o  <= temp(Bits);
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity DEMUX_GATE_BUS_1 is
  generic (
    Bits : integer;
    Default : integer );
  port (
    out_0: out std_logic_vector ((Bits-1) downto 0);
    out_1: out std_logic_vector ((Bits-1) downto 0);
    sel: in std_logic;
    p_in: in std_logic_vector ((Bits-1) downto 0) );
end DEMUX_GATE_BUS_1;

architecture Behavioral of DEMUX_GATE_BUS_1 is
begin
    out_0 <= p_in when sel = '0' else std_logic_vector(to_unsigned(Default, Bits));
    out_1 <= p_in when sel = '1' else std_logic_vector(to_unsigned(Default, Bits));
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity left_shift_with_carry_8085 is
  port (
    inotp: in std_logic_vector(7 downto 0);
    cy12: in std_logic;
    cy_sel: in std_logic;
    op: out std_logic_vector(7 downto 0);
    cy: out std_logic);
end left_shift_with_carry_8085;

architecture Behavioral of left_shift_with_carry_8085 is
  signal s0: std_logic_vector(8 downto 0);
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic_vector(8 downto 0);
begin
  s0(7 downto 0) <= inotp;
  s0(8) <= cy12;
  s1 <= s0(7);
  s2 <= s0(8);
  gate0: entity work.MUX_GATE_1
    port map (
      sel => cy_sel,
      in_0 => s1,
      in_1 => s2,
      p_out => s3);
  s4(0) <= s3;
  s4(1) <= s0(0);
  s4(2) <= s0(1);
  s4(3) <= s0(2);
  s4(4) <= s0(3);
  s4(5) <= s0(4);
  s4(6) <= s0(5);
  s4(7) <= s0(6);
  s4(8) <= s1;
  op <= s4(7 downto 0);
  cy <= s4(8);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity right_shift_with_carry_8085 is
  port (
    inotp: in std_logic_vector(7 downto 0);
    cy_in: in std_logic;
    cy_sel: in std_logic;
    op: out std_logic_vector(7 downto 0);
    cy: out std_logic);
end right_shift_with_carry_8085;

architecture Behavioral of right_shift_with_carry_8085 is
  signal s0: std_logic_vector(8 downto 0);
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic_vector(8 downto 0);
begin
  s0(7 downto 0) <= inotp;
  s0(8) <= cy_in;
  s1 <= s0(0);
  s2 <= s0(8);
  gate0: entity work.MUX_GATE_1
    port map (
      sel => cy_sel,
      in_0 => s1,
      in_1 => s2,
      p_out => s3);
  s4(0) <= s0(1);
  s4(1) <= s0(2);
  s4(2) <= s0(3);
  s4(3) <= s0(4);
  s4(4) <= s0(5);
  s4(5) <= s0(6);
  s4(6) <= s0(7);
  s4(7) <= s3;
  s4(8) <= s1;
  op <= s4(7 downto 0);
  cy <= s4(8);
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity MUX_GATE_2 is
  port (
    p_out: out std_logic;
    sel: in std_logic_vector (1 downto 0);
    
    in_0: in std_logic;
    in_1: in std_logic;
    in_2: in std_logic;
    in_3: in std_logic );
end MUX_GATE_2;

architecture Behavioral of MUX_GATE_2 is
begin
  with sel select
    p_out <=
      in_0 when "00",
      in_1 when "01",
      in_2 when "10",
      in_3 when "11",
      '0' when others;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;

entity DIG_D_FF is
  generic (
    Default: std_logic ); 
  port ( D  : in std_logic;
         C  : in std_logic;
         Q  : out std_logic;
         notQ : out std_logic );
end DIG_D_FF;

architecture Behavioral of DIG_D_FF is
   signal state : std_logic := Default;
begin
   Q    <= state;
   notQ <= NOT( state );

   process(C)
   begin
      if rising_edge(C) then
        state  <= D;
      end if;
   end process;
end Behavioral;


LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n1_bit_regitor is
  port (
    p_in: in std_logic;
    CLK: in std_logic;
    L: in std_logic;
    onotp: out std_logic);
end n1_bit_regitor;

architecture Behavioral of n1_bit_regitor is
  signal s0: std_logic;
  signal onotp_temp: std_logic;
begin
  gate0: entity work.MUX_GATE_1
    port map (
      sel => L,
      in_0 => onotp_temp,
      in_1 => p_in,
      p_out => s0);
  gate1: entity work.DIG_D_FF
    generic map (
      Default => '0')
    port map (
      D => s0,
      C => CLK,
      Q => onotp_temp);
  onotp <= onotp_temp;
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity n8_bit_register is
  port (
    p_IN: in std_logic_vector(7 downto 0);
    clk: in std_logic;
    L: in std_logic;
    onotp: out std_logic_vector(7 downto 0));
end n8_bit_register;

architecture Behavioral of n8_bit_register is
  signal s0: std_logic;
  signal s1: std_logic;
  signal s2: std_logic;
  signal s3: std_logic;
  signal s4: std_logic;
  signal s5: std_logic;
  signal s6: std_logic;
  signal s7: std_logic;
  signal s8: std_logic;
  signal s9: std_logic;
  signal s10: std_logic;
  signal s11: std_logic;
  signal s12: std_logic;
  signal s13: std_logic;
  signal s14: std_logic;
  signal s15: std_logic;
  signal s16: std_logic_vector(3 downto 0);
begin
  s12 <= p_IN(0);
  s8 <= p_IN(1);
  s10 <= p_IN(2);
  s14 <= p_IN(3);
  s4 <= p_IN(4);
  s0 <= p_IN(5);
  s2 <= p_IN(6);
  s6 <= p_IN(7);
  gate0: entity work.n1_bit_regitor
    port map (
      p_in => s0,
      CLK => clk,
      L => L,
      onotp => s1);
  gate1: entity work.n1_bit_regitor
    port map (
      p_in => s2,
      CLK => clk,
      L => L,
      onotp => s3);
  gate2: entity work.n1_bit_regitor
    port map (
      p_in => s4,
      CLK => clk,
      L => L,
      onotp => s5);
  gate3: entity work.n1_bit_regitor
    port map (
      p_in => s6,
      CLK => clk,
      L => L,
      onotp => s7);
  gate4: entity work.n1_bit_regitor
    port map (
      p_in => s8,
      CLK => clk,
      L => L,
      onotp => s9);
  gate5: entity work.n1_bit_regitor
    port map (
      p_in => s10,
      CLK => clk,
      L => L,
      onotp => s11);
  gate6: entity work.n1_bit_regitor
    port map (
      p_in => s12,
      CLK => clk,
      L => L,
      onotp => s13);
  gate7: entity work.n1_bit_regitor
    port map (
      p_in => s14,
      CLK => clk,
      L => L,
      onotp => s15);
  s16(0) <= s5;
  s16(1) <= s1;
  s16(2) <= s3;
  s16(3) <= s7;
  onotp(0) <= s13;
  onotp(1) <= s9;
  onotp(2) <= s11;
  onotp(3) <= s15;
  onotp(7 downto 4) <= s16;
end Behavioral;

LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity main is
  port (
    Acc: in std_logic_vector(7 downto 0);
    B: in std_logic_vector(7 downto 0);
    clk: in std_logic;
    instruction: in std_logic_vector(3 downto 0);
    Acc_out: out std_logic_vector(7 downto 0);
    B_out: out std_logic_vector(7 downto 0);
    flag: out std_logic_vector(7 downto 0));
end main;

architecture Behavioral of main is
  signal s0: std_logic_vector(1 downto 0);
  signal s1: std_logic_vector(7 downto 0);
  signal s2: std_logic_vector(7 downto 0);
  signal DAA: std_logic_vector(7 downto 0);
  signal carry: std_logic;
  signal DAA_sel: std_logic;
  signal s3: std_logic_vector(7 downto 0);
  signal s4: std_logic_vector(7 downto 0);
  signal s5: std_logic_vector(3 downto 0);
  signal s6: std_logic_vector(3 downto 0);
  signal s7: std_logic;
  signal s8: std_logic_vector(3 downto 0);
  signal ac: std_logic;
  signal n0: std_logic;
  signal s9: std_logic_vector(7 downto 0);
  signal p_not: std_logic_vector(7 downto 0);
  signal s10: std_logic;
  signal s11: std_logic_vector(7 downto 0);
  signal s12: std_logic_vector(7 downto 0);
  signal s13: std_logic_vector(7 downto 0);
  signal s14: std_logic_vector(7 downto 0);
  signal s15: std_logic;
  signal s16: std_logic_vector(7 downto 0);
  signal flag_temp: std_logic_vector(7 downto 0);
  signal cy: std_logic;
  signal s17: std_logic_vector(7 downto 0);
  signal s18: std_logic_vector(7 downto 0);
  signal Acc_out_temp: std_logic_vector(7 downto 0);
  signal s19: std_logic_vector(7 downto 0);
  signal s20: std_logic_vector(7 downto 0);
  signal s21: std_logic_vector(7 downto 0);
  signal s22: std_logic_vector(1 downto 0);
  signal s23: std_logic_vector(7 downto 0);
  signal s24: std_logic_vector(7 downto 0);
  signal s25: std_logic_vector(7 downto 0);
  signal s26: std_logic_vector(1 downto 0);
  signal n1: std_logic;
  signal s27: std_logic_vector(7 downto 0);
  signal s28: std_logic_vector(7 downto 0);
  signal cy_1: std_logic;
  signal cy_2: std_logic;
  signal s29: std_logic;
  signal cy_a: std_logic;
  signal s30: std_logic;
  signal s31: std_logic_vector(3 downto 0);
  signal s32: std_logic_vector(3 downto 0);
  signal s33: std_logic_vector(3 downto 0);
  signal n2: std_logic;
  signal n3: std_logic;
  signal s34: std_logic;
  signal s35: std_logic;
  signal s36: std_logic;
begin
  s1(3 downto 0) <= "0000";
  s1(7 downto 4) <= "0110";
  s2(3 downto 0) <= "0110";
  s2(7 downto 4) <= "0110";
  s19 <= (Acc AND B);
  s20 <= (Acc OR B);
  s21 <= (Acc XOR B);
  n0 <= instruction(0);
  n1 <= instruction(1);
  n2 <= instruction(2);
  n3 <= instruction(3);
  s26(0) <= n0;
  s26(1) <= n1;
  s22(0) <= n3;
  s22(1) <= n2;
  s34 <= (NOT n0 AND NOT n1);
  s36 <= (n2 AND n0 AND n3);
  DAA_sel <= (n2 AND n1 AND NOT n0);
  gate0: entity work.MUX_GATE_1
    port map (
      sel => DAA_sel,
      in_0 => n1,
      in_1 => '0',
      p_out => s10);
  gate1: entity work.MUX_GATE_1
    port map (
      sel => DAA_sel,
      in_0 => n3,
      in_1 => '0',
      p_out => s15);
  gate2: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 8)
    port map (
      sel => s15,
      in_0 => B,
      in_1 => "00000001",
      p_out => s3);
  gate3: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 8)
    port map (
      sel => s15,
      in_0 => Acc,
      in_1 => B,
      p_out => s9);
  p_not <= NOT s9;
  gate4: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 8)
    port map (
      sel => s10,
      in_0 => s9,
      in_1 => p_not,
      p_out => s11);
  gate5: entity work.MUX_GATE_BUS_2
    generic map (
      Bits => 8)
    port map (
      sel => s26,
      in_0 => s19,
      in_1 => s20,
      in_2 => s21,
      in_3 => p_not,
      p_out => s24);
  s5 <= s11(3 downto 0);
  s31 <= s11(7 downto 4);
  gate6: entity work.MUX_GATE_BUS_2
    generic map (
      Bits => 8)
    port map (
      sel => s0,
      in_0 => "00000000",
      in_1 => "00000110",
      in_2 => s1,
      in_3 => s2,
      p_out => DAA);
  gate7: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 8)
    port map (
      sel => DAA_sel,
      in_0 => s3,
      in_1 => DAA,
      p_out => s4);
  gate8: entity work.DIG_Add
    generic map (
      Bits => 4)
    port map (
      a => s5,
      b => s6,
      c_i => s7,
      s => s8,
      c_o => ac);
  s7 <= (carry AND n0);
  gate9: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 8)
    port map (
      sel => s10,
      in_0 => s12,
      in_1 => s13,
      p_out => s14);
  s16(0) <= cy;
  s16(1) <= '1';
  s16(2) <= NOT (Acc_out_temp(0) XOR Acc_out_temp(1) XOR Acc_out_temp(2) XOR Acc_out_temp(3) XOR Acc_out_temp(4) XOR Acc_out_temp(5) XOR Acc_out_temp(6) XOR Acc_out_temp(7));
  s16(3) <= '1';
  s16(4) <= ac;
  s16(5) <= '1';
  s16(6) <= NOT (Acc_out_temp(0) OR Acc_out_temp(1) OR Acc_out_temp(2) OR Acc_out_temp(3) OR Acc_out_temp(4) OR Acc_out_temp(5) OR Acc_out_temp(6) OR Acc_out_temp(7));
  s16(7) <= (cy_a AND s10);
  gate10: entity work.DEMUX_GATE_BUS_1
    generic map (
      Bits => 8,
      Default => 0)
    port map (
      sel => s15,
      p_in => s14,
      out_0 => s17,
      out_1 => s18);
  gate11: entity work.MUX_GATE_BUS_2
    generic map (
      Bits => 8)
    port map (
      sel => s22,
      in_0 => s17,
      in_1 => s23,
      in_2 => s24,
      in_3 => s25,
      p_out => Acc_out_temp);
  gate12: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 8)
    port map (
      sel => n1,
      in_0 => s27,
      in_1 => s28,
      p_out => s23);
  gate13: entity work.left_shift_with_carry_8085
    port map (
      inotp => Acc,
      cy12 => carry,
      cy_sel => n0,
      op => s27,
      cy => cy_1);
  gate14: entity work.right_shift_with_carry_8085
    port map (
      inotp => Acc,
      cy_in => carry,
      cy_sel => n0,
      op => s28,
      cy => cy_2);
  gate15: entity work.MUX_GATE_1
    port map (
      sel => n1,
      in_0 => cy_1,
      in_1 => cy_2,
      p_out => s29);
  gate16: entity work.MUX_GATE_2
    port map (
      sel => s22,
      in_0 => cy_a,
      in_1 => s29,
      in_2 => carry,
      in_3 => s30,
      p_out => cy);
  gate17: entity work.DIG_Add
    generic map (
      Bits => 4)
    port map (
      a => s31,
      b => s32,
      c_i => ac,
      s => s33,
      c_o => cy_a);
  gate18: entity work.MUX_GATE_1
    port map (
      sel => s34,
      in_0 => cy_a,
      in_1 => s35,
      p_out => s30);
  gate19: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 8)
    port map (
      sel => s36,
      in_0 => B,
      in_1 => s18,
      p_out => B_out);
  gate20: entity work.MUX_GATE_BUS_1
    generic map (
      Bits => 8)
    port map (
      sel => DAA_sel,
      in_0 => Acc,
      in_1 => s17,
      p_out => s25);
  gate21: entity work.n8_bit_register
    port map (
      p_IN => s16,
      clk => clk,
      L => '1',
      onotp => flag_temp);
  s12(3 downto 0) <= s8;
  s12(7 downto 4) <= s33;
  s6 <= s4(3 downto 0);
  s32 <= s4(7 downto 4);
  s13 <= NOT s12;
  carry <= flag_temp(0);
  s0(0) <= flag_temp(4);
  s0(1) <= carry;
  s35 <= NOT carry;
  Acc_out <= Acc_out_temp;
  flag <= flag_temp;
end Behavioral;
